version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: jogger-client
    ports:
      - "3000:3000" # Frontend on port 3000
    volumes:
      - ./client:/app # Mounts local code for live updates
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Optional: helps with live reloading in Docker
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: jogger-server
    ports:
      - "5000:5000" # Backend on port 5000
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo-db:27017/jogger
      - JWT_SECRET=your_secret_key
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongo-data:
