version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: jogger-server
    ports:
      - "5000:5000" # Exposes port 5000
    volumes:
      - ./server:/app # Mount local server code for live updates
      - /app/node_modules # Ensure node_modules is isolated in the container
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo-db:27017/jogger
      - JWT_SECRET=your_secret_key
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongo-data:
